### ISSUE TITLE
'install_dependencies.sh' references a non-existing repo

### ISSUE THREAD

**Issue by maccam912** [aws-deepracer/aws-deepracer-follow-the-leader-sample-project#8]
https://github.com/aws-deepracer/aws-deepracer-follow-the-leader-sample-project/blob/1b75e538fa06171589ecc2279cfce27cff1b5fa3/deepracer_follow_the_leader_ws/install_dependencies.sh#L18

https://github.com/jbnunn/rplidar_ros2 might be the closest one now.

**Comment by siddalingesha-ds** [comment]
Hi,

Thank you for reporting the issue. We have updated the script to point to the right repository.
